### ISSUE TITLE
검색 엔진 최적화 (SEO)

### ISSUE THREAD

**Issue by stunstunstun** [stunstunstun/hexo-theme-chiangmai#2]
### TODO

- [x] 네이버 검색 대상이 되도록 사이트 등록
- [x] Title & Description 잘 노출 되는지 확인
- [x] robots.txt
- [x] 오픈 그래프 설정
